version: "3.3"
services:
    spark-master:
        build: ./spark-master/
        container_name: spark-master
        hostname: spark-master
        ports:
            - "8080:8080"
            - "7077:7077"
        networks:
            spark-network:
                ipv4_address: 10.5.0.2
        volumes:
            - /mnt/spark/spark-apps:/opt/spark-apps
            - /mnt/spark/spark-data:/opt/spark-data
        environment:
            - "SPARK_LOCAL_IP=spark-master"
    spark-worker-1:
        build: ./spark-worker/
        container_name: spark-worker-1
        hostname: spark-worker-1
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        env_file: ./env/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-1"
        networks:
            spark-network:
                ipv4_address: 10.5.0.3
        volumes:
            - /mnt/spark/spark-apps:/opt/spark-apps
            - /mnt/spark/spark-data:/opt/spark-data
    spark-worker-2:
        build: ./spark-worker/
        container_name: spark-worker-2
        hostname: spark-worker-2
        depends_on:
            - spark-master
        ports:
            - "8082:8081"
        env_file: ./env/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-2"
        networks:
            spark-network:
                ipv4_address: 10.5.0.4
        volumes:
            - /mnt/spark/spark-apps:/opt/spark-apps
            - /mnt/spark/spark-data:/opt/spark-data
    spark-worker-3:
        build: ./spark-worker/
        container_name: spark-worker-3
        hostname: spark-worker-3
        depends_on:
            - spark-master
        ports:
            - "8083:8081"
        env_file: ./env/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-3"
        networks:
            spark-network:
                ipv4_address: 10.5.0.5
        volumes:
            - /mnt/spark/spark-apps:/opt/spark-apps
            - /mnt/spark/spark-data:/opt/spark-data
networks:
    spark-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/16
